// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPJ5NmwTDMMSzdL93BHSDQm826jKLjDA',
    appId: '1:677712160556:web:a6c515c56088077d276e89',
    messagingSenderId: '677712160556',
    projectId: 'fir-day78',
    authDomain: 'fir-day78.firebaseapp.com',
    storageBucket: 'fir-day78.appspot.com',
    measurementId: 'G-LVCTEKJKYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIlQl5ufMCW1KObQ4MNnTWTAxySWjTLA',
    appId: '1:677712160556:android:d0ae6515dfa8e2b7276e89',
    messagingSenderId: '677712160556',
    projectId: 'fir-day78',
    storageBucket: 'fir-day78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_GfpLkNJfBQo5V4s8UUMz_rGmCcrGCMc',
    appId: '1:677712160556:ios:1c716027d4430e21276e89',
    messagingSenderId: '677712160556',
    projectId: 'fir-day78',
    storageBucket: 'fir-day78.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_GfpLkNJfBQo5V4s8UUMz_rGmCcrGCMc',
    appId: '1:677712160556:ios:6ff9785ab294d268276e89',
    messagingSenderId: '677712160556',
    projectId: 'fir-day78',
    storageBucket: 'fir-day78.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
